# Generated by Django 4.2.1 on 2023-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_cover"),
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book_id",
            field=models.ManyToManyField(to="book.book"),
        ),
    ]
