# Generated by Django 4.2.1 on 2023-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hard"), ("SOFT", "Soft")],
                default="SOFT",
                max_length=4,
            ),
        ),
    ]
